const PATHS = {
  profile: '/profile/:userId',
  messenger: '/messenger/:userId',
  chat: '/messenger/:userId/chat/:user2Id',
  board: '/board/:userId',
  board_create: '/board/:userId/create',
  board_show: '/board/:userId/post/:postId',
  board_edit: '/board/:userId/post/:postId/edit',
  settings: '/settings/:userId',
  password_settings: '/settings/:userId/password-settings',
  profile_settings: '/settings/:userId/profile-settings',
  logout: '/logout/:userId',
  login: '/login',
  users_show: '/users/:userId',
  users_create: '/users/:userId/create',
  users_edit: '/users/:userId/user/:editedUserId/edit',
  system: '/system/:userId',
  positions: '/system/:userId/positions',
  office_locations: '/system/:userId/office-locations',
  departments: '/system/:userId/departments',
  posts: '/system/:userId/posts',
  users: '/system/:userId/users',
};

export default PATHS;
