const authorizedUserTypes = {
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  AUTHENTICATE_USER_REQUEST: 'AUTHENTICATE_USER_REQUEST',
  AUTHENTICATE_USER_SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
  AUTHENTICATE_USER_FAILURE: 'AUTHENTICATE_USER_FAILURE',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  UPDATE_FRIENDS_REQUEST: 'UPDATE_FRIENDS_REQUEST',
  UPDATE_FRIENDS_SUCCESS: 'UPDATE_FRIENDS_SUCCESS',
  UPDATE_FRIENDS_FAILURE: 'UPDATE_FRIENDS_FAILURE',
  UPDATE_AUTH_USER_PASSWORD_REQUEST: 'UPDATE_AUTH_USER_PASSWORD_REQUEST',
  UPDATE_AUTH_USER_PASSWORD_SUCCESS: 'UPDATE_AUTH_USER_PASSWORD_SUCCESS',
  UPDATE_AUTH_USER_PASSWORD_FAILURE: 'UPDATE_AUTH_USER_PASSWORD_FAILURE',
  SET_AUTH_USER_ERROR: 'SET_AUTH_USER_ERROR',
  UPDATE_AUTH_USER: 'UPDATE_AUTH_USER',
};

export { authorizedUserTypes };
