export enum jobFunctionsTypes {
  GET_ALL_JOB_FUNCTIONS_REQUEST = 'GET_ALL_JOB_FUNCTIONS_REQUEST',
  GET_ALL_JOB_FUNCTIONS_SUCCESS = 'GET_ALL_JOB_FUNCTIONS_SUCCESS',
  GET_ALL_JOB_FUNCTIONS_FAILURE = 'GET_ALL_JOB_FUNCTIONS_FAILURE',
  CREATE_JOB_FUNCTION_REQUEST = 'CREATE_JOB_FUNCTION_REQUEST',
  CREATE_JOB_FUNCTION_SUCCESS = 'CREATE_JOB_FUNCTION_SUCCESS',
  CREATE_JOB_FUNCTION_FAILURE = 'CREATE_JOB_FUNCTION_FAILURE',
  UPDATE_JOB_FUNCTION_REQUEST = 'UPDATE_JOB_FUNCTION_REQUEST',
  UPDATE_JOB_FUNCTION_SUCCESS = 'UPDATE_JOB_FUNCTION_SUCCESS',
  UPDATE_JOB_FUNCTION_FAILURE = 'UPDATE_JOB_FUNCTION_FAILURE',
  DELETE_JOB_FUNCTION_REQUEST = 'DELETE_JOB_FUNCTION_REQUEST',
  DELETE_JOB_FUNCTION_SUCCESS = 'DELETE_JOB_FUNCTION_SUCCESS',
  DELETE_JOB_FUNCTION_FAILURE = 'DELETE_JOB_FUNCTION_FAILURE',
}
