export enum jobFunctionsTypes {
  GET_ALL_JOB_FUNCTIONS_REQUEST = 'GET_ALL_JOB_FUNCTIONS_REQUEST',
  GET_ALL_JOB_FUNCTIONS_SUCCESS = 'GET_ALL_JOB_FUNCTIONS_SUCCESS',
  GET_ALL_JOB_FUNCTIONS_FAILURE = 'GET_ALL_JOB_FUNCTIONS_FAILURE',
}
