export enum positionStatusesTypes {
  GET_ALL_POSITION_STATUSES_REQUEST = 'GET_ALL_POSITION_STATUSES_REQUEST',
  GET_ALL_POSITION_STATUSES_SUCCESS = 'GET_ALL_POSITION_STATUSES_SUCCESS',
  GET_ALL_POSITION_STATUSES_FAILURE = 'GET_ALL_POSITION_STATUSES_FAILURE',
}
