export enum positionStatusesTypes {
  GET_ALL_POSITION_STATUSES_REQUEST = 'GET_ALL_POSITION_STATUSES_REQUEST',
  GET_ALL_POSITION_STATUSES_SUCCESS = 'GET_ALL_POSITION_STATUSES_SUCCESS',
  GET_ALL_POSITION_STATUSES_FAILURE = 'GET_ALL_POSITION_STATUSES_FAILURE',
  CREATE_POSITION_STATUS_REQUEST = 'CREATE_POSITION_STATUS_REQUEST',
  CREATE_POSITION_STATUS_SUCCESS = 'CREATE_POSITION_STATUS_SUCCESS',
  CREATE_POSITION_STATUS_FAILURE = 'CREATE_POSITION_STATUS_FAILURE',
  UPDATE_POSITION_STATUS_REQUEST = 'UPDATE_POSITION_STATUS_REQUEST',
  UPDATE_POSITION_STATUS_SUCCESS = 'UPDATE_POSITION_STATUS_SUCCESS',
  UPDATE_POSITION_STATUS_FAILURE = 'UPDATE_POSITION_STATUS_FAILURE',
}
