export enum prioritiesTypes {
  GET_ALL_PRIORITIES_REQUEST = 'GET_ALL_PRIORITIES_REQUEST',
  GET_ALL_PRIORITIES_SUCCESS = 'GET_ALL_PRIORITIES_SUCCESS',
  GET_ALL_PRIORITIES_FAILURE = 'GET_ALL_PRIORITIES_FAILURE',
}
