export enum scopesTypes {
  GET_ALL_SCOPES_REQUEST = 'GET_ALL_SCOPES_REQUEST',
  GET_ALL_SCOPES_SUCCESS = 'GET_ALL_SCOPES_SUCCESS',
  GET_ALL_SCOPES_FAILURE = 'GET_ALL_SCOPES_FAILURE',
  CREATE_SCOPE_REQUEST = 'CREATE_SCOPE_REQUEST',
  CREATE_SCOPE_SUCCESS = 'CREATE_SCOPE_SUCCESS',
  CREATE_SCOPE_FAILURE = 'CREATE_SCOPE_FAILURE',
  UPDATE_SCOPE_REQUEST = 'UPDATE_SCOPE_REQUEST',
  UPDATE_SCOPE_SUCCESS = 'UPDATE_SCOPE_SUCCESS',
  UPDATE_SCOPE_FAILURE = 'UPDATE_SCOPE_FAILURE',
}
