export enum statisticsTypesTypes {
  GET_ALL_STATISTICS_TYPES_REQUEST = 'GET_ALL_STATISTICS_TYPES_REQUEST',
  GET_ALL_STATISTICS_TYPES_SUCCESS = 'GET_ALL_STATISTICS_TYPES_SUCCESS',
  GET_ALL_STATISTICS_TYPES_FAILURE = 'GET_ALL_STATISTICS_TYPES_FAILURE',
}
