export enum technologiesTypes {
  GET_ALL_TECHNOLOGIES_REQUEST = 'GET_ALL_TECHNOLOGIES_REQUEST',
  GET_ALL_TECHNOLOGIES_SUCCESS = 'GET_ALL_TECHNOLOGIES_SUCCESS',
  GET_ALL_TECHNOLOGIES_FAILURE = 'GET_ALL_TECHNOLOGIES_FAILURE',
}
